import { registerUser, loginUser } from "./auth.service";
import {
  uploadFile,
  getAllFilesByUserId,
  getFileById,
  getFileWithVersions,
  deleteFile,
  downloadFileVersion,
  downloadLatestFile,
  restoreFileVersion,
  findDuplicateFilesForUser,
  findDuplicatesByFileIdForUser,
  updateFileDescription,
  getFileMetadata,
  updateFileMetadata,
  deleteFileMetadata,
  addFileMetadata,
  searchFiles,
} from "./file.service";
import { grantPermission } from "./permission.service";
import { logger, requestLogger } from "./logger.service";

export {
  registerUser,
  loginUser,
  uploadFile,
  getAllFilesByUserId,
  getFileById,
  getFileWithVersions,
  deleteFile,
  downloadFileVersion,
  downloadLatestFile,
  restoreFileVersion,
  grantPermission,
  logger,
  requestLogger,
  findDuplicateFilesForUser,
  findDuplicatesByFileIdForUser,
  updateFileDescription,
  updateFileMetadata,
  getFileMetadata,
  addFileMetadata,
  deleteFileMetadata,
  searchFiles,
};
