import { register, login } from "./auth.controller";
import { getProfile } from "./profile.controller";
import {
  uploadFiles,
  grantPermissions,
  getFile,
  downloadLatest,
  getFileVersions,
  downloadSpecificVersion,
  updateFile,
  updateMetadata,
  getMetadata,
  addMetadata,
  deleteMetadata,
  deleteFileById,
  getAllFiles,
  getDuplicateFiles,
  getDuplicatesByFileId,
  restoreFile,
  searchFiles,
} from "./file.controller";
import { prometheusMetrics } from "./prometheus.controller";

export {
  register,
  login,
  getProfile,
  uploadFiles,
  grantPermissions,
  getFile,
  downloadLatest,
  getFileVersions,
  downloadSpecificVersion,
  prometheusMetrics,
  updateFile,
  updateMetadata,
  addMetadata,
  getMetadata,
  deleteMetadata,
  deleteFileById,
  getAllFiles,
  getDuplicateFiles,
  getDuplicatesByFileId,
  restoreFile,
  searchFiles,
};
